import joblib
from sklearn.feature_extraction.text import TfidfVectorizer

def check_review(review):
    model = joblib.load('\model\model2.pkl')
    vectorizer = joblib.load('\model\_vectorizer2.pkl')  # Load the same vectorizer used during training
    # Transform the text into numerical features using the vectorizer
    X_text = vectorizer.transform([review])

    # Make predictions
    prediction = model.predict(X_text)

    # Print prediction result
    if prediction[0] == 'human':
        result = "This review is likely to be human-written."
        print(result)
        return result
    else:
        result = "This review is likely to be generated by AI."
        print(result)
        return result

