import streamlit as st
import joblib
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
from colorama import Fore
from aichecker import check_review
from main import get_amazon_reviews, main

st.title('Amazon Review Checker')

user_input = st.text_area("Enter the Amazon link of the product")

if st.button('Predict'):
    count=0
    reviews = get_amazon_reviews(user_input)
    st.info(f"Total reviews found: {len(reviews)}")
    for i, review in enumerate(reviews, start=1):
        result = check_review(review)
        if result=='This review is likely to be generated by AI.' :
            #st.info(f"Review {i}\n:  {review} \n  {result}\n\n")
            count+=1
        else :
            #st.info(f"Review {i}\n:  {review} \n {result}\n\n")
            pass
    st.info(f"Percentage of AI generated reviews found: {(count/len(reviews))*100:.2f}%")   
